image: maven:latest

build:
  stage: build
  script: mvn compile --batch-mode

test:
  stage: test
  script: mvn test --batch-mode
  except:
    - testing

pages:
  stage: deploy
  script:
    - mvn javadoc:javadoc --batch-mode
    - mv src/main/javadoc public/
  artifacts:
    paths:
      - public
  only:
    - development